[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029D09F0D510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6354dd5f1005a99499828913e1f8f47
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029D09F0F340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6354dd5f1005a99499828913e1f8f47
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029D09F0F4F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6354dd5f1005a99499828913e1f8f47