{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756067918, "stop": 1757756067978}], "start": 1757756063938, "stop": 1757756067978}], "start": 1757756063938, "stop": 1757756067978}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756067978, "stop": 1757756067998}, {"name": "输入登录凭据", "status": "passed", "start": 1757756067998, "stop": 1757756072819}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "d81f2b9b-bcf2-45d6-a3f9-6672fb7bd32c-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "ddb58d9a-a1da-4b45-a437-b48921ff074a-attachment.html", "type": "text/html"}], "start": 1757756072819, "stop": 1757756075963}], "attachments": [{"name": "截图_test_valid_user_login", "source": "03c8da0a-0cd0-4827-a410-2ea162f4a68d-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "aa354a03-3fe2-459e-a392-c2250d1146e9-attachment.txt", "type": "text/plain"}], "start": 1757756063938, "stop": 1757756075963, "uuid": "188086af-8935-4132-b94b-58891dcc5b37", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户认证功能"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "18852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}