{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757753452859, "stop": 1757753452932}], "start": 1757753443827, "stop": 1757753452932}], "start": 1757753443827, "stop": 1757753452932}, {"name": "验证登录表单可见", "status": "passed", "start": 1757753452932, "stop": 1757753452956}, {"name": "输入登录凭据", "status": "passed", "start": 1757753452956, "stop": 1757753457240}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "3251c890-11ab-4bea-af84-58e501348ac2-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "46b986d7-56f9-49ca-807c-37659b090829-attachment.html", "type": "text/html"}], "start": 1757753457240, "stop": 1757753460426}], "attachments": [{"name": "截图_test_valid_user_login", "source": "77780653-2b4f-465f-8818-80f6990f7289-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "aa495df8-b7f7-43e2-8991-c5848d245ccb-attachment.txt", "type": "text/plain"}], "start": 1757753443826, "stop": 1757753460427, "uuid": "876a3e50-e512-456b-ad35-b47b5e09f7fa", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "story", "value": "用户登录"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "用户认证功能"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}