{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756046069, "stop": 1757756046141}], "start": 1757756040630, "stop": 1757756046141}], "start": 1757756040630, "stop": 1757756046141}, {"name": "验证登录表单可见", "status": "passed", "start": 1757756046141, "stop": 1757756046162}, {"name": "输入登录凭据", "status": "passed", "start": 1757756046162, "stop": 1757756050910}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "11062b21-c293-4b21-8c6a-2a24942df33e-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "14066fd2-8c89-47cb-87dc-425d26b14f9d-attachment.html", "type": "text/html"}], "start": 1757756050910, "stop": 1757756054070}], "attachments": [{"name": "截图_test_valid_user_login", "source": "e66a52ac-c8f9-4072-b575-71fa0dd018ec-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "f19b3cb1-3924-4f64-8ec6-f6371cec749a-attachment.txt", "type": "text/plain"}], "start": 1757756040630, "stop": 1757756054070, "uuid": "657ff4ef-0fd3-446d-a7a6-4c02395e4935", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户认证功能"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "18852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}