{"name": "有效用户登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False", "trace": "tests\\test_user_authentication.py:147: in test_valid_user_login\n    self.assert_with_screenshot(\ntests\\base_test.py:297: in assert_with_screenshot\n    assert condition, message\nE   AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nE   assert False"}, "description": "测试有效用户能够成功登录", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757750284922, "stop": 1757750284981}], "start": 1757750277429, "stop": 1757750284981}], "start": 1757750277429, "stop": 1757750284981}, {"name": "验证登录表单可见", "status": "passed", "start": 1757750284983, "stop": 1757750285004}, {"name": "输入登录凭据", "status": "passed", "start": 1757750285004, "stop": 1757750290309}, {"name": "验证登录成功", "status": "failed", "statusDetails": {"message": "AssertionError: 登录应该成功并跳转，但仍在登录页面: https://automationexercise.com/login\nassert False\n", "trace": "  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\test_user_authentication.py\", line 147, in test_valid_user_login\n    self.assert_with_screenshot(\n  File \"D:\\LAB\\Selenium-Pytest-POM\\tests\\base_test.py\", line 297, in assert_with_screenshot\n    assert condition, message\n"}, "attachments": [{"name": "Screenshot_assertion_failed", "source": "4ac00ef4-0b18-4f9d-8502-f1cb4d93272c-attachment.png", "type": "image/png"}, {"name": "Page Source", "source": "09f26539-87c6-4a9b-8c02-47295e1c4e64-attachment.html", "type": "text/html"}], "start": 1757750290309, "stop": 1757750293464}], "attachments": [{"name": "截图_test_valid_user_login", "source": "c8c3ce6f-91c5-464d-bd7e-f85cf4aca860-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "d2fa21d0-952e-4c99-8dfc-e4e9075fe343-attachment.txt", "type": "text/plain"}], "start": 1757750277413, "stop": 1757750293465, "uuid": "35078f27-ce28-4df3-8af4-3df595b19035", "historyId": "046d5fc4db15d4f3441a52fe936e97c6", "testCaseId": "046d5fc4db15d4f3441a52fe936e97c6", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_valid_user_login", "labels": [{"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "feature", "value": "用户认证功能"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "用户登录"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "20396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}